import Link from "next/link";
import { ArrowRight, Check, ChevronRight, FileHeart, FileText, FolderOpen, HeartPulse, Search, ShieldCheck, Sparkles, UploadCloud } from "lucide-react";
import { Brand } from "@/components/brand";
import { ThemeToggle } from "@/components/theme-toggle";

export default function Home() {
  return <main className="landing">
    <header className="site-header wrap"><Brand/><nav className="landing-nav" aria-label="Main navigation"><a href="#benefits">Why Health Dossier</a><a href="#how-it-works">How it works</a></nav><div className="header-actions"><ThemeToggle compact/><Link className="button button-outline" href="/signup">Get started <ArrowRight size={17}/></Link></div></header>
    <section className="hero wrap">
      <div className="hero-copy"><span className="eyebrow"><span className="eyebrow-dot"/> A CLEARER WAY TO KEEP YOUR HEALTH STORY</span><h1>Every record.<br/>One place.<br/><em>More peace of mind.</em></h1><p>From a routine blood test to the report you need years later, Health Dossier gives your medical documents a place that feels organized and easy to use.</p><div className="hero-actions"><Link className="button button-primary" href="/signup">Get started <ArrowRight size={18}/></Link><a className="hero-text-link" href="#how-it-works">See how it works <ChevronRight size={18}/></a></div></div>
      <div className="hero-visual" aria-label="Illustration of an organized medical record"><div className="visual-orbit"/><div className="illustration-card"><div className="illustration-top"><span className="illustration-icon"><FolderOpen size={24}/></span><span>YOUR HEALTH DOSSIER</span><span className="illustration-check"><Check size={16}/></span></div><h2>Ready when you need it.</h2><p className="illustration-subtitle">The right document, without the search.</p><div className="illustration-row"><span className="illustration-file blue"><FileText size={20}/></span><div><b>Annual health check</b><small>Laboratory report · 21 Aug 2026</small></div><span className="illustration-row-check"><Check size={14}/></span></div><div className="illustration-row"><span className="illustration-file green"><FileHeart size={20}/></span><div><b>Prescription</b><small>Care plan · 12 May 2026</small></div><span className="illustration-row-check"><Check size={14}/></span></div><div className="illustration-row"><span className="illustration-file pale"><HeartPulse size={20}/></span><div><b>Vaccination record</b><small>Immunization · 4 Feb 2025</small></div><span className="illustration-row-check"><Check size={14}/></span></div></div><div className="visual-tag"><Search size={16}/> Find what matters, faster</div><div className="visual-spark"><Sparkles size={17}/></div></div>
    </section>
    <section className="value-strip"><div className="wrap value-strip-inner"><span><FolderOpen size={18}/> A home for your documents</span><span><Search size={18}/> Quick search and filters</span><span><ShieldCheck size={18}/> Your choices, clearly shown</span></div></section>
    <section id="benefits" className="benefits-section wrap"><div className="section-heading"><span className="section-kicker">BUILT FOR REAL LIFE</span><h2>Less digging. More clarity.</h2><p>When your records are organized, the information you need is easier to find and understand.</p></div><div className="benefit-cards"><article className="benefit-card"><span className="benefit-card-icon"><UploadCloud size={25}/></span><h3>Bring it together</h3><p>Add your PDFs and images with a date, document type, and care provider.</p><span className="benefit-card-number">01</span></article><article className="benefit-card"><span className="benefit-card-icon"><Search size={25}/></span><h3>Find it in a moment</h3><p>Search titles and notes, or narrow your library by record type.</p><span className="benefit-card-number">02</span></article><article className="benefit-card"><span className="benefit-card-icon"><FileHeart size={25}/></span><h3>Keep the original close</h3><p>Preview a document and download the original whenever you need it.</p><span className="benefit-card-number">03</span></article></div></section>
    <section id="how-it-works" className="workflow-section"><div className="wrap workflow-grid"><div className="workflow-copy"><span className="section-kicker">SIMPLE FROM THE START</span><h2>A little order goes a long way.</h2><p>Start with one document. Build a library that makes more sense each time you add to it.</p><Link className="button button-primary" href="/signup">Start your dossier <ArrowRight size={18}/></Link></div><div className="workflow-steps"><div><span>1</span><div><strong>Choose how to continue</strong><p>Continue with Google, Apple, or your phone number.</p></div></div><div><span>2</span><div><strong>Add a medical document</strong><p>Keep the original file alongside the details you care about.</p></div></div><div><span>3</span><div><strong>Find it when you need it</strong><p>Search, review, and download from one calm space.</p></div></div></div></div></section>
    <section className="landing-final wrap"><div><span className="section-kicker">YOUR STORY, BETTER ORGANIZED</span><h2>Make room for what matters.</h2><p>Take the first step toward a clearer view of your medical records.</p></div><Link className="button button-light" href="/signup">Get started <ArrowRight size={18}/></Link></section>
    <footer className="footer wrap"><Brand/><p>Your health story, beautifully organized.</p></footer>
  </main>;
}
